Nearly there, import issues...
(virt-env)sforman@callix:~/Desktop/phoenixbureau$ python -m Xerblin --roost=./tmp --init
INFO:INIT_REPO:<Repo at './tmp'> created.
INFO:INIT_REPO:./tmp/system.pickle written.
INFO:INIT_REPO:Files staged: system.pickle
INFO:INIT_REPO:Initial commit done. c7eeb67d49d50027c68ab3c57e220265a765c339
INFO:COMMIT:commit e7b93c6bb42c2f3696ea1f980ef0663a8cb1049f
INFO:werkzeug: * Running on http://127.0.0.1:5000/
INFO:werkzeug: * Restarting with reloader
Traceback (most recent call last):
  File "/home/sforman/Desktop/phoenixbureau/Xerblin/__main__.py", line 57, in <module>
    from Xerblin.gitstore import initialize_repo
ImportError: No module named Xerblin.gitstore

(virt-env)sforman@callix:~/Desktop/phoenixbureau$ python -m Xerblin --roost=./tmp --init
CRITICAL:INIT_REPO:Repository already exists at './tmp'
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/sforman/Desktop/phoenixbureau/Xerblin/__main__.py", line 59, in <module>
    initialize_repo(args.roost, ROOT)
  File "Xerblin/gitstore.py", line 78, in initialize_repo
    raise ValueError('Repository already exists at %r' % (path,))
ValueError: Repository already exists at './tmp'

(virt-env)sforman@callix:~/Desktop/phoenixbureau$ python -m Xerblin --roost=./tmp
INFO:COMMIT:commit 017f5c05be21721f07f6cc5cd74849bdae94d079
INFO:werkzeug: * Running on http://127.0.0.1:5000/
INFO:werkzeug: * Restarting with reloader
Traceback (most recent call last):
  File "/home/sforman/Desktop/phoenixbureau/Xerblin/__main__.py", line 62, in <module>
    from Xerblin.gitstore import SYSTEM_PICKLE
ImportError: No module named Xerblin.gitstore